> # Data Cleansing

In [40]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
import re
%matplotlib inline
import seaborn as sns
import datetime as dt
import time

> # Event
- C – Closest approach to a coast, not followed by a landfall
- G – Genesis
- I – An intensity peak in terms of both pressure and wind
- L – Landfall (center of system crossing a coastline)
- P – Minimum in central pressure
- R – Provides additional detail on the intensity of the cyclone when rapid changes are underway
- S – Change of status of the system
- T – Provides additional detail on the track (position) of the cyclone
- W – Maximum sustained wind speed

> # Status
- TD – Tropical cyclone of tropical depression intensity (< 34 knots)
- TS – Tropical cyclone of tropical storm intensity (34-63 knots)
- HU – Tropical cyclone of hurricane intensity (> 64 knots)
- EX – Extratropical cyclone (of any intensity)
- SD – Subtropical cyclone of subtropical depression intensity (< 34 knots)
- SS – Subtropical cyclone of subtropical storm intensity (> 34 knots)
- LO – A low that is neither a tropical cyclone, a subtropical cyclone, nor an extratropical cyclone (of any intensity)
- WV – Tropical Wave (of any intensity)
- DB – Disturbance (of any intensity)

## __Cleansing Data Pacific.csv__

In [41]:
a = pd.read_csv('pacific.csv')

In [42]:
pacific = pd.read_csv('pacific.csv')

In [43]:
pacific[['Status']]=pacific[['Status']].apply(lambda x : x.str.strip())

In [44]:
pacific['Date'] = pd.to_datetime(pacific['Date'], format= '%Y%m%d')

In [45]:
pacific.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26137 entries, 0 to 26136
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                26137 non-null  object
 1   Name              26137 non-null  object
 2   Date              26137 non-null  datetime64[ns]
 3   Time              26137 non-null  int64
 4   Event             26137 non-null  object
 5   Status            26137 non-null  object
 6   Latitude          26137 non-null  object
 7   Longitude         26137 non-null  object
 8   Maximum Wind      26137 non-null  int64
 9   Minimum Pressure  26137 non-null  int64
 10  Low Wind NE       26137 non-null  int64
 11  Low Wind SE       26137 non-null  int64
 12  Low Wind SW       26137 non-null  int64
 13  Low Wind NW       26137 non-null  int64
 14  Moderate Wind NE  26137 non-null  int64
 15  Moderate Wind SE  26137 non-null  int64
 16  Moderate Wind SW  26137 non-null  int64
 17  Moderate Wind NW  26137 non-null  int64
 18  High Wind NE      26137 non-null  int64
 19  High Wind SE      26137 non-null  int64
 20  High Wind SW      26137 non-null  int64
 21  High Wind NW      26137 non-null  int64
dtypes: datetime64[ns](1), int64(15), object(6)
memory usage: 4.4+ MB

gw belom ngerti re.match

In [46]:
#  ganti latitude longitude ke float
def alp_floats(s):
    m = re.match('[+-]?\d+(\.\d+)?', s)
    return float(m.group(0)) if m is not None and m.start() == 0 else 0
Latitude_new= []
Longitude_new = []
for i in pacific['Latitude']:
    Latitude_new.append(i)
for i in pacific['Longitude']:
    Longitude_new.append(i)
pacific['Latitude'] = [alp_floats(i) for i in Latitude_new]
pacific['Longitude'] = [alp_floats(i) for i in Longitude_new]

In [47]:
pacific.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26137 entries, 0 to 26136
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                26137 non-null  object
 1   Name              26137 non-null  object
 2   Date              26137 non-null  datetime64[ns]
 3   Time              26137 non-null  int64
 4   Event             26137 non-null  object
 5   Status            26137 non-null  object
 6   Latitude          26137 non-null  float64
 7   Longitude         26137 non-null  float64
 8   Maximum Wind      26137 non-null  int64
 9   Minimum Pressure  26137 non-null  int64
 10  Low Wind NE       26137 non-null  int64
 11  Low Wind SE       26137 non-null  int64
 12  Low Wind SW       26137 non-null  int64
 13  Low Wind NW       26137 non-null  int64
 14  Moderate Wind NE  26137 non-null  int64
 15  Moderate Wind SE  26137 non-null  int64
 16  Moderate Wind SW  26137 non-null  int64
 17  Moderate Wind NW  26137 non-null  int64
 18  High Wind NE      26137 non-null  int64
 19  High Wind SE      26137 non-null  int64
 20  High Wind SW      26137 non-null  int64
 21  High Wind NW      26137 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(15), object(4)
memory usage: 4.4+ MB

In [48]:
# Imputation
for column in pacific.columns:
    missing_cnt = pacific[column][pacific[column] == -999].count()
    print('Missing Values in column {col} = '.format(col = column) , missing_cnt )
    if missing_cnt!= 0:
#         print('in ' , column)
        mean = round(pacific[column][pacific[column] != -999 ].mean())
#         print("mean",mean)
        index = pacific.loc[pacific[column] == -999 , column].index
#         print("index" , index )
        pacific.loc[pacific[column] == -999 , column] = mean
#         print(df.loc[index , column])

Missing Values in column ID =  0
Missing Values in column Name =  0
Missing Values in column Date =  0
Missing Values in column Time =  0
Missing Values in column Event =  0
Missing Values in column Status =  0
Missing Values in column Latitude =  0
Missing Values in column Longitude =  0
Missing Values in column Maximum Wind =  0
Missing Values in column Minimum Pressure =  12804
Missing Values in column Low Wind NE =  19750
Missing Values in column Low Wind SE =  19750
Missing Values in column Low Wind SW =  19750
Missing Values in column Low Wind NW =  19750
Missing Values in column Moderate Wind NE =  19750
Missing Values in column Moderate Wind SE =  19750
Missing Values in column Moderate Wind SW =  19750
Missing Values in column Moderate Wind NW =  19750
Missing Values in column High Wind NE =  19750
Missing Values in column High Wind SE =  19750
Missing Values in column High Wind SW =  19750
Missing Values in column High Wind NW =  19750

In [49]:
pacific

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,EP011949,UNNAMED,1949-06-11,0,,TS,20.2,106.3,45,995,...,27,35,13,11,9,11,5,4,3,5
1,EP011949,UNNAMED,1949-06-11,600,,TS,20.2,106.4,45,995,...,27,35,13,11,9,11,5,4,3,5
2,EP011949,UNNAMED,1949-06-11,1200,,TS,20.2,106.7,45,995,...,27,35,13,11,9,11,5,4,3,5
3,EP011949,UNNAMED,1949-06-11,1800,,TS,20.3,107.7,45,995,...,27,35,13,11,9,11,5,4,3,5
4,EP011949,UNNAMED,1949-06-12,0,,TS,20.4,108.6,45,995,...,27,35,13,11,9,11,5,4,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,EP222015,SANDRA,2015-11-28,1200,,LO,21.7,109.0,35,1002,...,0,0,0,0,0,0,0,0,0,0
26133,EP222015,SANDRA,2015-11-28,1800,,LO,22.4,108.7,30,1007,...,0,0,0,0,0,0,0,0,0,0
26134,EP222015,SANDRA,2015-11-29,0,,LO,23.1,108.3,30,1008,...,0,0,0,0,0,0,0,0,0,0
26135,EP222015,SANDRA,2015-11-29,600,,LO,23.5,107.9,25,1009,...,0,0,0,0,0,0,0,0,0,0
26136,EP222015,SANDRA,2015-11-29,1200,,LO,24.2,107.7,20,1010,...,0,0,0,0,0,0,0,0,0,0

In [50]:
#  ganti format jam
pacific['Time'] = pacific['Time'].astype('object')
def hhmm(time):
    time = str(time)
    digits = re.findall(r'\d', time)
    t = ''
    if len(digits) == 1:
        t ='0{i}00'.format(i =time)
    elif len(digits) == 2:
        t = '{i}00'.format(i =time)
    elif len(digits) == 3:
        t = '0{i}'.format(i =time)
    else:
        t = time
    return t
pacific['Time'] = pacific['Time'].apply(hhmm)
pacific['Time'] = pd.to_datetime(pacific['Time'] , format='%H%M').dt.time

In [51]:
# ganti status jadi kategorikal
pacific['Status'] = pacific['Status'].astype('category')

In [52]:
# drop data ID dan Event
pacific = pacific.drop(columns = ['ID' , 'Event'])

Data ID dan Event tidak relevan untuk model

In [53]:
pacific

,Name,Date,Time,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,UNNAMED,1949-06-11,00:00:00,TS,20.2,106.3,45,995,40,35,27,35,13,11,9,11,5,4,3,5
1,UNNAMED,1949-06-11,06:00:00,TS,20.2,106.4,45,995,40,35,27,35,13,11,9,11,5,4,3,5
2,UNNAMED,1949-06-11,12:00:00,TS,20.2,106.7,45,995,40,35,27,35,13,11,9,11,5,4,3,5
3,UNNAMED,1949-06-11,18:00:00,TS,20.3,107.7,45,995,40,35,27,35,13,11,9,11,5,4,3,5
4,UNNAMED,1949-06-12,00:00:00,TS,20.4,108.6,45,995,40,35,27,35,13,11,9,11,5,4,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,SANDRA,2015-11-28,12:00:00,LO,21.7,109.0,35,1002,60,0,0,0,0,0,0,0,0,0,0,0
26133,SANDRA,2015-11-28,18:00:00,LO,22.4,108.7,30,1007,0,0,0,0,0,0,0,0,0,0,0,0
26134,SANDRA,2015-11-29,00:00:00,LO,23.1,108.3,30,1008,0,0,0,0,0,0,0,0,0,0,0,0
26135,SANDRA,2015-11-29,06:00:00,LO,23.5,107.9,25,1009,0,0,0,0,0,0,0,0,0,0,0,0
26136,SANDRA,2015-11-29,12:00:00,LO,24.2,107.7,20,1010,0,0,0,0,0,0,0,0,0,0,0,0

In [54]:
# Untuk EDA
pacific.to_csv('Pacific_Cleansed.csv')